spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/creddit-main-server
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    log-request-details: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
server:
  error:
    include-stacktrace: always